config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, 
             length: { minimum: 2, maximum: 25}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: {case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to do that ..."
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit

  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update

    if @article.update(article_params)
      flash[:success] = "Successfully Updated!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    
    def article_params
      params.require(:article).permit(:title, :description)
    end
    
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "Not yours."
        redirect_to root_path
      end
    end
    

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Created!"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def show 
    
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = " Only admin can action"
      redirect_to categories_path
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
   
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Good job! You just logged in the website."
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Something wrong..."
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You just logged out, good bye ;)"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles are deleted."
    redirect_to users_path
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
   if current_user != @user and !current_user.admin?
     flash[:danger] = "Not yours."
     redirect_to root_path
   end
  end
  
  def requre_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin user can delete somebody"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class:"img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
          <div class="article-body">
          <%= truncate(article.description, length:50) %>
            <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user%>,
                <%= time_ago_in_words(article.created_date) if article.created_date%> ago,
                last updated: <%= time_ago_in_words(article.updated_date) if article.updated_date%> ago</small>
            </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          </div>
          <%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this Article", article_path(article), method: :delete, data: { confirm: "are you sure?" }, class: "btn btn-xs-btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class='form-group'>
        <div class="control-lable col-sm-2">
          <%= f.label :title %> <br/>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class:"form-control", placeholder: "Title"%>
        </div>
      </div>    

      <div class='form-group'>
        <div class="control-lable col-sm-2">
          <%= f.label :description %><br/>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class:"form-control", placeholder: "Body of Article"%>
        </div>
      </div>    
    
      <div class='form-group'>
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.submit class:"btn btn-warning btn-lg" %>
        </div>
      </div>
        
    <% end %>
    <div class="col-xs-4 col-xs-offset-2">
      [ <%= link_to "Cancel request and Back to articles listing.", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1> Edit existing articles. </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center"> Listing all articles. </h1>

<div align='center'>
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align='center'>
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1> Create a new article! </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> Title: <%= @article.title %></h2>
  


  <div class="col-xs-8 col-xs-offset-2">
    <% if @article.user %>
      <div class="row">
        created by: 
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article_title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li><small>
          <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
        </small></li>
      </div>
    <% end %>
    
    <h4 class="center"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
  </div>
  
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-warning" %>
      <%= link_to "Delete this Article", article_path(@article), method: :delete, data: { confirm: "are you sure?" }, class: "btn btn-xs-btn-secondary" %>
    <% end %>
    
    <%= link_to "View all Articles", articles_path, class: "btn btn-xs btn-secondary" %>
  </div>

app/views/categories/index.html.erb
<h1 align="center">Listing all categories</h1>

<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="articles-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class='form-group'>
    <div class="control-lable col-sm-2">
      <%= f.label :name %> <br/>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class:"form-control", placeholder: "Enter Category"%>
    </div>
  </div>    

  <div class='form-group'>
    <div class="col-sm-10 col-sm-offset-2">
      <%= f.submit class:"btn btn-warning btn-lg" %>
    </div>
  </div>
    
<% end %>
<div class="col-xs-4 col-xs-offset-2">
  [ <%= link_to "Cancel request and Back to articles listing.", articles_path %> ]
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright: Lin Shao Chieh
      FB: pommfiro2
      IG: @linshaochieh
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
  </div>
</div>

<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "AlphaBlog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if logged_in? %>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <li><%= link_to 'Edit your profile', edit_user_path(current_user) %></li>
        <li><%= link_to 'View your profile', user_path(current_user) %></li>
        <li>Your Profile<%= 'Admin' if current_user.admin? %></li>
        <li><%= link_to 'New Article', new_article_path %></li>
      <% else %>
        <li><%= link_to 'Log in', login_path %></li>
        <li><%= link_to 'Sign up', signup_path %></li>
      <% end %>
      <li class="nav-item">
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/pages/about.erb
<p>
  
SCHEDULE
*[F]=已額滿; [Go!]=已開班尚未額滿; [-1]=差一位可開班; [R]=尚未開班
*請點擊課名看完整介紹:)

<%= link_to image_tag('alex01.jpg'), 'http://www.mydearteacher.com/schedule.html' %>

</p>

app/views/pages/home.erb
<div class="center jumbotron">
  <h1> ALPHA BLOG </h1>
  <%= link_to "Sign Up", signup_path, class: "btn btn-warning btn-lg btn-xlarge" %>
  
</div>

<p>
  
MYDEARTEACHER
豐富生活的英文體驗
​MDT提供小班制討論課程與生活體驗，
學員可以在喜歡的主題中自然地使用英文。
我們相信英文是座橋梁，走過了就是更寬廣的世界。
完整課表請見連結。

</p>

<%= link_to "Alpha Blog", articles_path %> | <%= link_to 'About', about_path %>

app/views/shared/_errors.html.erb
<!--<% if obj.errors.any? %>-->
<!--  <div class="row">-->
<!--    <div class="col-xs-8 col-xs-offset-2">-->
<!--      <div class="panel panel-danger">-->
<!--        <div class="panel-heading">-->
<!--          <h2 class="panel-title">-->
<!--          <%= pluralize(obj.errors.count, "error") %>-->
<!--          prohibited this article from saved:-->
<!--          </h2>-->
<!--          <div class="panel-body">-->
<!--            <ul>-->
              <!--<% obj.errors.full_message.each do |msg| %>-->
<!--                <li><% msg %></li>-->
<!--              <% end %>-->
<!--            </ul>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>    -->
<!--  </div>-->
<!--<% end %>-->

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class='col-xs-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class='form-group'>
        <div class="control-lable col-sm-2">
          <%= f.label :username %> <br/>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class:"form-control", placeholder: "Enter Username"%>
        </div>
      </div>    

      <div class='form-group'>
        <div class="control-lable col-sm-2">
          <%= f.label :email %><br/>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class:"form-control", placeholder: "Enter Email"%>
        </div>
      </div>    
    
      <div class='form-group'>
        <div class="control-lable col-sm-2">
          <%= f.label :password %><br/>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class:"form-control", placeholder: "Enter Password"%>
        </div>
      </div>    
    
      <div class='form-group'>
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class:"btn btn-warning btn-lg") %>
        </div>
      </div>
        
    <% end %>
    <div class="col-xs-4 col-xs-offset-2">
      [ <%= link_to "Cancel request and Back to articles listing.", articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 algin = "center"> Edit you account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center"> All Alpha Bloggers </h1>

<div align='center'>
  <%= will_paginate %>
</div>

<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article_title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li><small>
          <%= pluralize(user.articles.count, "article") if user.articles %>
        </small></li>
        <% if logged_in? and current_user.admin? %>
         <li><% link_to "Delete the user", user_path(user), method: :delete, 
             data: { confirm: "Are you sure?" }%></li>
        <% end %>
      </div>
    </div>
  </ul>
  
<% end %>

<div align='center'>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align ="center"> Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %> </h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align="center"><%= @user.username%>'s articles</h4>

<div class="center">
  <%= will_paginate @user_articles%>
  <%= render 'articles/article', obj: @user_articles %>
</div>